version: '3'
services:
  website_checker:
    build: .
    command: python -m website_monitor.website_checker
    environment:
    - WEBSITE_MONITOR_CONFIG_PATH=/app/config
  database_writer:
    build: .
    command: python -m website_monitor.database_writer
    environment:
    - WEBSITE_MONITOR_CONFIG_PATH=/app/config
