# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: website_availability_metrics.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="website_availability_metrics.proto",
    package="",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n"website_availability_metrics.proto\x1a\x1fgoogle/protobuf/timestamp.proto"\xd6\x01\n\x1aWebsiteAvailabilityMetrics\x12,\n\x08\x64\x61tetime\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06target\x18\x02 \x01(\t\x12\x1a\n\x12http_response_time\x18\x03 \x01(\x02\x12\x13\n\x0bhttp_status\x18\x04 \x01(\x05\x12\x1b\n\x11regexp_match_null\x18\x05 \x01(\x08H\x00\x12\x1c\n\x12regexp_match_value\x18\x06 \x01(\x08H\x00\x42\x0e\n\x0cregexp_matchb\x06proto3',
    dependencies=[
        google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,
    ],
)


_WEBSITEAVAILABILITYMETRICS = _descriptor.Descriptor(
    name="WebsiteAvailabilityMetrics",
    full_name="WebsiteAvailabilityMetrics",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="datetime",
            full_name="WebsiteAvailabilityMetrics.datetime",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="target",
            full_name="WebsiteAvailabilityMetrics.target",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="http_response_time",
            full_name="WebsiteAvailabilityMetrics.http_response_time",
            index=2,
            number=3,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="http_status",
            full_name="WebsiteAvailabilityMetrics.http_status",
            index=3,
            number=4,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="regexp_match_null",
            full_name="WebsiteAvailabilityMetrics.regexp_match_null",
            index=4,
            number=5,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="regexp_match_value",
            full_name="WebsiteAvailabilityMetrics.regexp_match_value",
            index=5,
            number=6,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="regexp_match",
            full_name="WebsiteAvailabilityMetrics.regexp_match",
            index=0,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
    ],
    serialized_start=72,
    serialized_end=286,
)

_WEBSITEAVAILABILITYMETRICS.fields_by_name[
    "datetime"
].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_WEBSITEAVAILABILITYMETRICS.oneofs_by_name["regexp_match"].fields.append(
    _WEBSITEAVAILABILITYMETRICS.fields_by_name["regexp_match_null"]
)
_WEBSITEAVAILABILITYMETRICS.fields_by_name[
    "regexp_match_null"
].containing_oneof = _WEBSITEAVAILABILITYMETRICS.oneofs_by_name["regexp_match"]
_WEBSITEAVAILABILITYMETRICS.oneofs_by_name["regexp_match"].fields.append(
    _WEBSITEAVAILABILITYMETRICS.fields_by_name["regexp_match_value"]
)
_WEBSITEAVAILABILITYMETRICS.fields_by_name[
    "regexp_match_value"
].containing_oneof = _WEBSITEAVAILABILITYMETRICS.oneofs_by_name["regexp_match"]
DESCRIPTOR.message_types_by_name[
    "WebsiteAvailabilityMetrics"
] = _WEBSITEAVAILABILITYMETRICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WebsiteAvailabilityMetrics = _reflection.GeneratedProtocolMessageType(
    "WebsiteAvailabilityMetrics",
    (_message.Message,),
    {
        "DESCRIPTOR": _WEBSITEAVAILABILITYMETRICS,
        "__module__": "website_availability_metrics_pb2"
        # @@protoc_insertion_point(class_scope:WebsiteAvailabilityMetrics)
    },
)
_sym_db.RegisterMessage(WebsiteAvailabilityMetrics)


# @@protoc_insertion_point(module_scope)
